### ISSUE TITLE
FR: Compatibility for Windows 10

### ISSUE THREAD

**Issue by tjsuominen** [ChrisAnd1998/TaskbarXI#17]
Add compatibility for Windows 10

**Comment by ChrisAnd1998** [comment]
@tjsuominen I have to inform you about TaskbarX ;)
https://github.com/ChrisAnd1998/TaskbarX

TaskbarX is for Windows 10
TaskbarXI is for Windows 11

Since Windows 11 the taskbar works very differently from Windows 10.
So thats why i decided to make TaskbarXI. Instead of adding Windows 11 compatibility to TaskbarX.

**Comment by tjsuominen** [comment]
Ah, acknowledged. Hope the development continues for that too 😉

**Comment by ChrisAnd1998** [comment]
It will 😉
