### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by alp196996** [ChrisAnd1998/TaskbarXI#23]
How do you remove it idk how please help

**Comment by Asad-13** [comment]
First of all, reach a state when the PC is running, and TaskbarXI is also running without any run-time issues. Then, go to Task Manager through this combination: 'Ctrl+Shift+Esc'. If the task manager is not showing much information (such as Status, Memory, CPU, etc.), click on 'More Details' on the lower-left corner of the window.

Then, under 'Background Processes', scroll down and look for the process named "TaskbarXI" and left click on it. Then on the bottom-right corner, select 'End Task'.

You wouldn't see any change right away, and now you will have to further navigate in the Task Manager. Under 'Windows Processes' look for 'Windows Explorer' and right click on it. From the drop down menu, select 'Restart'. This will take a bit of time, so it is recommended you do not use your computer for about 15~ seconds. After this, you should see that your taskbar is back to looking normal now. I think that after this you can uninstall it too, since this is the way the developer has highlighted in order to stop it. "Use Task manager to kill the process and restart Explorer.exe to remove it. A GUI will be added later.."

Hope this works.

**Comment by ChrisAnd1998** [comment]
@Asad-13 Thank you for taking the time to solve this! 😁

**Comment by Janwi03** [comment]
@ChrisAnd1998 Even in task manager there is no trace of taskbarXI but its there in downloaded folder.
Please help me resolve it.
