### ISSUE TITLE
Fantastic TaskbarXI for Win11 since TaskbarX for Win10 but some suggestions

### ISSUE THREAD

**Issue by ezad3280** [ChrisAnd1998/TaskbarXI#62]
Really great app to enhanced the looks of my Windows 11 taskbar. It works smoothly and I am glad that I purchased the app to support the Developer since TaskbarX for Windows 10. Both prices are cheap and affordable. 

Just to add something to the Developer as below :-

1. Do you mind to add in the 'Style' options similar like TaskbarX? I do love the 'Transparent Gradient' style from TaskbarX for Win10. 

2. Please add the options to make the taskbar in full-size in desktop mode rather than full-size when maximized window.

3. What is the meaning of 'Smooth Resize'? I don't see the Taskbar can be resize when the options selected.

4. I saw you guys updated the version which can turn on the BLUR under Experimental but saw none in the options.

5. Certain times all the icons in the taskbar are vanished. Need to restart the Windows Explorer in task manager to bring it back.

6. Hope my suggestions above will take into consideration from your end. 

Can't hardly wait to see further updates and support. 

Do reach me out by replying here, Microsoft Store (Ratings and Reviews) or email.

Thanks @ChrisAnd1998 @PrincessAkira @officialLennox

**Comment by ChrisAnd1998** [comment]
@ezad3280 Thank you for your support! Styling options will be coming soon but, need some work to fix the bugs they currently have. That's also the reason why the "Blur" option is not displayed in the configurator yet ;)
"Smooth resize" resizes the taskbar using an animation. So instead of resizing instantly it will expand and shrink smoothly. Just like TaskbarX i hope to add even more different animations in the future. When the styling options are in then there are enough options to keep the taskbar full-size.

It seems like you have found a bug! Soon I will be testing it on different hardware to see if I can reproduce it.

Everything you mentioned will be worked on ;)

**Comment by ezad3280** [comment]
Hi @ChrisAnd1998 

Splendid! and I am glad to hear it.

FYI. Screenshot attached as a proof regarding the missing icon after I turn on my PC.

Kindly look into it and fix it soonest possible if you so kind.

Thanks
![Screenshot 2022-01-26 174944](https://user-images.githubusercontent.com/98422436/151143011-d6447634-7ca3-45e2-8e5e-cce18b33c0f7.png)
.
